package com.challenge.fidoreader.fidoReader

const val CBOR_CODE_CTAP1_ERR_SUCCESS       			  = "00"	//Indicates successful response.
const val CBOR_CODE_CTAP1_ERR_INVALID_COMMAND			  = "01"	//The command is not a valid CTAP command.
const val CBOR_CODE_CTAP1_ERR_INVALID_PARAMETER			  = "02"	//The command included an invalid parameter.
const val CBOR_CODE_CTAP1_ERR_INVALID_LENGTH			  = "03"	//Invalid message or item length.
const val CBOR_CODE_CTAP1_ERR_INVALID_SEQ				  = "04"	//Invalid message sequencing.
const val CBOR_CODE_CTAP1_ERR_TIMEOUT					  = "05"	//Message timed out.
const val CBOR_CODE_CTAP1_ERR_CHANNEL_BUSY				  = "06"	//Channel busy. Client SHOULD retry the request after a short delay. Note that the client may abort the transaction if the command is no longer relevant.
const val CBOR_CODE_CTAP1_ERR_LOCK_REQUIRED				  = "0A"	//Command requires channel lock.
const val CBOR_CODE_CTAP1_ERR_INVALID_CHANNEL			  = "0B"	//Command not allowed on this cid.
const val CBOR_CODE_CTAP2_ERR_CBOR_UNEXPECTED_TYPE		  = "11"	//Invalid/unexpected CBOR error.
const val CBOR_CODE_CTAP2_ERR_INVALID_CBOR				  = "12"	//Error when parsing CBOR.
const val CBOR_CODE_CTAP2_ERR_MISSING_PARAMETER			  = "14"	//Missing non-optional parameter.
const val CBOR_CODE_CTAP2_ERR_LIMIT_EXCEEDED			  = "15"	//Limit for number of items exceeded.
const val CBOR_CODE_CTAP2_ERR_UNSUPPORTED_EXTENSION		  = "16"	//Unsupported extension.
const val CBOR_CODE_CTAP2_ERR_CREDENTIAL_EXCLUDED		  = "19"	//Valid credential found in the exclude list.
const val CBOR_CODE_CTAP2_ERR_PROCESSING				  = "21"	//Processing (Lengthy operation is in progress).
const val CBOR_CODE_CTAP2_ERR_INVALID_CREDENTIAL		  = "22"	//Credential not valid for the authenticator.
const val CBOR_CODE_CTAP2_ERR_USER_ACTION_PENDING		  = "23"	//Authentication is waiting for user interaction.
const val CBOR_CODE_CTAP2_ERR_OPERATION_PENDING			  = "24"	//Processing, lengthy operation is in progress.
const val CBOR_CODE_CTAP2_ERR_NO_OPERATIONS				  = "25"	//No request is pending.
const val CBOR_CODE_CTAP2_ERR_UNSUPPORTED_ALGORITHM		  = "26"	//Authenticator does not support requested algorithm.
const val CBOR_CODE_CTAP2_ERR_OPERATION_DENIED			  = "27"	//Not authorized for requested operation.
const val CBOR_CODE_CTAP2_ERR_KEY_STORE_FULL			  = "28"	//Internal key storage is full.
const val CBOR_CODE_CTAP2_ERR_NO_OPERATION_PENDING		  = "2A"	//No outstanding operations.
const val CBOR_CODE_CTAP2_ERR_UNSUPPORTED_OPTION		  = "2B"	//Unsupported option.
const val CBOR_CODE_CTAP2_ERR_INVALID_OPTION			  = "2C"	//Not a valid option for current operation.
const val CBOR_CODE_CTAP2_ERR_KEEPALIVE_CANCEL			  = "2D"	//Pending keep alive was cancelled.
const val CBOR_CODE_CTAP2_ERR_NO_CREDENTIALS			  = "2E"	//No valid credentials provided.
const val CBOR_CODE_CTAP2_ERR_USER_ACTION_TIMEOUT		  = "2F"	//Timeout waiting for user interaction.
const val CBOR_CODE_CTAP2_ERR_NOT_ALLOWED				  = "30"	//Continuation command, such as, authenticatorGetNextAssertion not allowed.
const val CBOR_CODE_CTAP2_ERR_PIN_INVALID				  = "31"	//PIN Invalid.
const val CBOR_CODE_CTAP2_ERR_PIN_BLOCKED				  = "32"	//PIN Blocked.
const val CBOR_CODE_CTAP2_ERR_PIN_AUTH_INVALID			  = "33"	//PIN authentication,pinUvAuthParam, verification failed.
const val CBOR_CODE_CTAP2_ERR_PIN_AUTH_BLOCKED			  = "34"	//PIN authentication,pinUvAuthParam, blocked. Requires power recycle to reset.
const val CBOR_CODE_CTAP2_ERR_PIN_NOT_SET				  = "35"	//No PIN has been set.
const val CBOR_CODE_CTAP2_ERR_PIN_REQUIRED				  = "36"	//PIN is required for the selected operation.
const val CBOR_CODE_CTAP2_ERR_PIN_POLICY_VIOLATION		  = "37"	//PIN policy violation. Currently only enforces minimum length.
const val CBOR_CODE_CTAP2_ERR_PIN_TOKEN_EXPIRED			  = "38"	//pinUvAuthToken expired on authenticator.
const val CBOR_CODE_CTAP2_ERR_REQUEST_TOO_LARGE			  = "39"	//Authenticator cannot handle this request due to memory constraints.
const val CBOR_CODE_CTAP2_ERR_ACTION_TIMEOUT			  = "3A"	//The current operation has timed out.
const val CBOR_CODE_CTAP2_ERR_UP_REQUIRED				  = "3B"	//User presence is required for the requested operation.
const val CBOR_CODE_CTAP2_ERR_UV_BLOCKED				  = "3C"	//Built in UV is blocked.
const val CBOR_CODE_CTAP1_ERR_OTHER						  = "7F"	//Other unspecified error.
const val CBOR_CODE_CTAP2_ERR_SPEC_LAST					  = "DF"	//CTAP 2 spec last error.
const val CBOR_CODE_CTAP2_ERR_EXTENSION_FIRST			  = "E0"	//Extension specific error.
const val CBOR_CODE_CTAP2_ERR_EXTENSION_LAST			  = "EF"	//Extension specific error.
const val CBOR_CODE_CTAP2_ERR_VENDOR_FIRST				  = "F0"	//Vendor specific error.
const val CBOR_CODE_CTAP2_ERR_VENDOR_LAST				  = "FF"	//Vendor specific error.